### ISSUE TITLE
Support assign attachments

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-local_downloadcenter#15]
One of our users noticed that you can't download all attachments of an assignment at once, neither in the activity itself nor in the downloadcenter.

Would you be willing to add support for the core "assign" activity? I have already implemented it and can make a pull request if you like.

**Comment by goggo24** [comment]
You are right - at the moment it's only possible to download pages, books, folder, files, lightbox galeries and student folders, We try to expand our plugin support via downloadcenter and our next step would have been assignment :) We do not have any resources for that right now, but if you can provide as a pull request, we will be happy to have a look.

Only for completeness:  in ASSIGNMENT it's possible for the teacher to download all files - it's hidden behind the gear icon.  SNEAK PREVIEW: we are also working just on publishing a local assignment plugin, with witch the teacher can download all files with an own name scheme like [name]_[filename] (it's working with tags) - so that all filenames have the same structure ;) Our teachers use it a lot - coming soon for the community!

**Comment by goggo24** [comment]
Thank you for the confirmation ;) I will take it in our next backlog refinement.

**Comment by t-schroeder** [comment]
I've added my implementation.

I've talked with my colleagues about this and they raised a valid point. When you download only the attached files for an assignment through the downloadcenter with the implementation being the way I have it now, you don't get the actual assignment text. So we will probably be looking to solve this in another way. Maybe we can change the activity itself in core to display a "Download all" button if there are more than X attachments. Anyway, I just posted the implementation in case you want to use it in the downloadcenter. But if you do, you should probably also add some code that downloads the description text as well.

Then there's the general ambiguity of which files are downloaded. If you include an assignment by ticking its checkbox will you get the attached files? Will you get your own submission? Both? What if you are a teacher: Do you download the students' submission this way?

As you can see there are a few reasons that speak against this. I'm therefore closing this issue.

**Comment by goggo24** [comment]
Assignments can be downlaoded from teacher or students since downloadcenter v.3.9.0
Also our local assignmet plugin is already published => https://moodle.org/plugins/local_assignsubmission_download - have fun!
