### ISSUE TITLE
Hidden files within an available Section are appearing in Download list

### ISSUE THREAD

**Issue by dcombes** [academic-moodle-cooperation/moodle-local_downloadcenter#29]
Our lecturers often hide some documents from students that are located within an available page Section. However, all the content of that Section, including these hidden files, are appearing in the Download Centre's list. It would be better, in line with the purpose of hidding content, if Download Centre is able to determine the hidden/visible status at the individual document level rather than at the page Section/Topic level, and so to not list hidden items that are located within available Sections.

This issue seems to have the same root cause (hidden status determined at page section level rather than individual document level) as the issue raised under "Files from available activities in hidden sections, available through stealth mode, are not included #20".

Thanks for your work on this, great plugin.
David

**Comment by goggo24** [comment]
Are you talking about hidden files in a available section? If yes, hidden files in available section can be downloaded only by teacher via download center. As a student the hidden file doesn't appear in the list - so the availability setting takes effect. 

I just tried it with our newest version (v4.2.1 - 2023050501):
<img width="1180" alt="hiddenfile" src="https://github.com/academic-moodle-cooperation/moodle-local_downloadcenter/assets/16721900/c8e8e46a-40da-4e34-af18-6eb28afa7c69">

Regarding #20: For students files "available but not shown on course page" are not listed too via download center. Only for teachers, because for this role the availability setting has no effect.

Or did you mean something else? If so, can you please give us a step-by-step description, so we can recreate it. Thanks, Eva.

**Comment by dcombes** [comment]
Thanks Eva for confirming. Yes you are, of course, correct! Apologies, we were testing whilst in ‘teacher’ mode. This looks great and works well for us.
David
