### ISSUE TITLE
suggestion- link location

### ISSUE THREAD

**Issue by rimacher** [academic-moodle-cooperation/moodle-local_downloadcenter#7]
Hello,

Would it be possible to allow admins to set the location of the download center link? 

Currently it's located in the navigation block and our university would prefer it in the administration block.

**Comment by goggo24** [comment]
Hey, thanks for the suggestion. At the moment we don't have any admin settings for this local plugin. We integrated the downloadcenter purposely in the navigation block, because this block appears (automatically) in every course and futhermore the admin block cannot be seen by students, but we developed the plugin primarily for/with students. We ourselves use boost theme and there it's also located under "grades" before the "topic"-area. 
Currently we see no need to create an admin setting page and prefer to focus our ressources on other AMC plugins. Sorry, Eva.
